language: csharp
solution: TheiaVR.sln
install:
  - nuget restore TheiaVR.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory TestsRunners
script:
  - xbuild /p:Configuration=Release solution-name.sln
  - mono ./TestsRunners/NUnit.Runners.3.6.1/tools/nunit-console.exe ./TheiaVRTests/bin/Release/TheiaVRTests.dll